apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None # This makes it a Headless Service
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432