apiVersion: v1
kind: Service
metadata:
  name: try-k8s-web-client-service
spec:
  type: NodePort
  selector:
    app: try-k8s-web-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Choose an available port on your nodes (30000-32767)